export const WarChestABI = [
  {
    type: 'function',
    name: 'factionPrizePool',
    inputs: [{ name: 'faction', type: 'uint8', internalType: 'uint8' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'settled',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'seasonStart',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'passiveRatePerSecond',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lastAccrue',
    inputs: [{ name: 'regionId', type: 'uint16', internalType: 'uint16' }],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimed',
    inputs: [
      { name: 'regionId', type: 'uint16', internalType: 'uint16' },
      { name: 'faction', type: 'uint8', internalType: 'uint8' },
      { name: 'user', type: 'address', internalType: 'address' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'regionFactionContribTotal',
    inputs: [
      { name: 'regionId', type: 'uint16', internalType: 'uint16' },
      { name: 'faction', type: 'uint8', internalType: 'uint8' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'finalScore',
    inputs: [{ name: 'faction', type: 'uint8', internalType: 'uint8' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'factionPayout',
    inputs: [{ name: 'faction', type: 'uint8', internalType: 'uint8' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claim',
    inputs: [{ name: 'regionIds', type: 'uint16[]', internalType: 'uint16[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'accruePassive',
    inputs: [{ name: 'regionId', type: 'uint16', internalType: 'uint16' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'RewardClaimed',
    inputs: [
      { name: 'user', type: 'address', indexed: true, internalType: 'address' },
      { name: 'regionId', type: 'uint16', indexed: true, internalType: 'uint16' },
      { name: 'faction', type: 'uint8', indexed: true, internalType: 'uint8' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
  },
  {
    type: 'event',
    name: 'PassiveAccrued',
    inputs: [
      { name: 'regionId', type: 'uint16', indexed: true, internalType: 'uint16' },
      { name: 'faction', type: 'uint8', indexed: true, internalType: 'uint8' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
  },
] as const;
